### ISSUE TITLE
Validacija telefona

### ISSUE THREAD

**Issue by mathildaa** [SoftverInzenjeringETFSA/SI2015Tim12#15]
Komponenta:
dodavanje hotela

commit ID:
2f47d83

Opis problema:
u polje za telefon prilikom registracije novog hotela se mogu upisivati slova, te ne postoji nikakva validacija. 
Put do problema: login (uloga administratora) -> Hoteli -> Dodaj Hotel

Dobijeni rezultat:
Registrovan hotel sa brojem telefona "hhh"

Očekivani rezultat:
Obavještenje o grešci, nemogućnost registracije

**Comment by adnatahic** [comment]
ispravljeno
