### ISSUE TITLE
Datum početka i kraja visoke sezone

### ISSUE THREAD

**Issue by mathildaa** [SoftverInzenjeringETFSA/SI2015Tim12#16]
Komponenta:
Forma za Administratora, dodavanje hotela

commit ID:
2f47d83

Opis problema:
Moguće je dodati datum kraja visoke sezone koji je PRIJE datuma početka visoke sezone

Izlaz: 
Uspješna registracija

Dobijeni rezultat:
Registrovan hotel

Očekivani rezultat:
Neuspješna registracija, obavijest o grešci

**Comment by adnatahic** [comment]
Ispravljeno
