### ISSUE TITLE
Nemogućnost registracije dva hotela istog naziva a na drugim lokacijama

### ISSUE THREAD

**Issue by mathildaa** [SoftverInzenjeringETFSA/SI2015Tim12#17]
Komponenta:
Forma za administratora, dodavanje hotela

commit ID:
2f47d83

Opis problema:
U SRSu je pretpostavka za uspješno kreiranje hotela da hotel već ne postoji u bazi, međutim kada se pokuša dodati hotel sa istim imenom, a različitom adresom kao neki koji već postoji u bazi (a to nedvojbeno nisu isti hoteli, nego dva različita hotela samo sa istim imenom), sistem odbija registraciju hotela.

Dobijeni rezultat:
Nemogućnost registracije hotela sa istim imenom, obavijest ne daje razlog zbog kog nije uspješna registracija

Očekivani rezultat:
Uspješna registracija hotela

**Comment by avelic** [comment]
Dodana logika koja to omogucuje

**Comment by avelic** [comment]
Moguce je dodati dva hotela sa razlicitom adresom, a sa istim imenom i u prethodnim verzijama app tako da update bio nepotreban i s tim je issue ivalid.
