### ISSUE TITLE
Nemogućnost prijave na sistem

### ISSUE THREAD

**Issue by ncongo** [SoftverInzenjeringETFSA/SI2015Tim12#18]
Komponenta: Prilikom prijave na sistem

Opis problema: Nije se moguće prijaviti na sistem sa podacima iz baze. Javlja se izuzetak.

Koraci za reproduciranje problema:
1. Pokretanje aplikacije
2. Unos podataka za prijavu na sistem (Korisničko ime: kenanprses, šifra: Sitim12
                                                            ili korisničko ime:  kagent, šifra: Sitim12
                                                            ili korisničko ime:  ksupervizor, šifra: Sitim12)
http://prntscr.com/b4u50e

Dobijeni rezultat:
ERROR UnitOfWork:56 - java.lang.NullPointerException
http://prntscr.com/b4u0t1

Očekivani rezultat:
Pokretanje neke forme za korištenje sistema.

**Comment by adnatahic** [comment]
Potrebno je importovati bazu tim 12_v4_final_version. U ostalim skriptama ne postoji tabela Postavke, zbog čega baci NullPointerException. Već je prijavljeno nepostojeće uputstvo za import baze, što je i razlog ovome, ( #13 ), tako da ovaj issue nije validan.

**Comment by kprses** [comment]
Kod nas login radi vjerovatno je do podataka u bazi... Treba importovati pravi .sql fajl

**Comment by kprses** [comment]
Nije validno zbog upravo gore navedenog razloga tj. zbog toga što nedostaje neki podatak u bazi odnosno nije importovan korektan .sql fajl
