### ISSUE TITLE
Ne radi opcija za editovanje sobe

### ISSUE THREAD

**Issue by mathildaa** [SoftverInzenjeringETFSA/SI2015Tim12#19]
Komponenta:
Forma za administratora -> Hoteli -> Pregledaj sobe -> Edituj sobu

commit ID:
2f47d83

Opis problema:
Klik na button Edituj izbacuje obavještenje da je uspješno KREIRANA soba, a ne modifikovana

Dobijeni rezultat:
Uspješno kreirana soba

Očekivani rezultat:
Uspješno editovana soba

**Comment by avelic** [comment]
Typo greska ispravljena
