### ISSUE TITLE
Ne postoji validacija JMBG

### ISSUE THREAD

**Issue by mathildaa** [SoftverInzenjeringETFSA/SI2015Tim12#20]
Komponenta:
Forma za administratora -> Rezervacije -> Kreiranje rezervacije

commit ID:
2f47d83

Opis problema:
Kao JMBG se može unijeti slovo ili bilo šta, ne postoji obavještenje da se desila greška

Dobijeni rezultat:
Registrovana rezervacija

Očekivani rezultat:
Obavještenje o greškama, zahtjev za novim unosom

**Comment by adnatahic** [comment]
ispravljeno
