### ISSUE TITLE
Ne postoji obavještenje zbog čega nije uspjela registracija

### ISSUE THREAD

**Issue by mathildaa** [SoftverInzenjeringETFSA/SI2015Tim12#21]
Komponenta:
Forma za administratora -> Rezervacije -> Kreiranje rezervacije

commit ID:
2f47d83

Opis problema:
Ukoliko se kod registracije nove rezervacije ne unese hotel i željene sobe, ne postoji obavještenje o razlogu neuspješne registracije, niti obavještenje da registracija nije uspjela, samo button ne proizvodi nikakav efekat

Dobijeni rezultat:
nema efekta button

Očekivani rezultat:
Obavještenje o greškama, zahtjev za novim unosom

**Comment by adnatahic** [comment]
ispravljeno
