### ISSUE TITLE
Ne postoji validacija telefona pri kreiranju rezervacije

### ISSUE THREAD

**Issue by psimanic1** [SoftverInzenjeringETFSA/SI2015Tim12#25]
Komponenta:
Forma za administratora -> Rezervacije -> Kreiranje rezervacije

commit ID:
c64c205

Opis problema:
Prilikom kreiranja rezervacije, validacija broja telefona postoji samo na prazno polje, ne i na unos slova.

Dobijeni rezultat:
Kreirana rezervacija s brojem telefona kao slova

Očekivani rezultat:
Traženje ponovnog unosa validnih informacija.

**Comment by mathildaa** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2015Tim12/issues/15

već prijavljeno

**Comment by psimanic1** [comment]
Druga komponenta, u #15 je validacija pri dodavanu hotela, ovo je prilikom kreiranja rezervacije...

**Comment by adnatahic** [comment]
ispravljeno
