### ISSUE TITLE
Validacija JMBG pri kreiranju korisničkog računa

### ISSUE THREAD

**Issue by psimanic1** [SoftverInzenjeringETFSA/SI2015Tim12#26]
Komponenta:
Kreiranje korisničkog računa

commit ID:
e047178

Opis problema:
Prilikom kreiranja novog korisničkog računa, moguće je kreirati račun s JMBG koji već postoji, program ne izbacuje grešku.

Dobijeni rezultat:
Kreiran korisnički račun

Očekivani rezultat:
Informacija o već postojećem JMBG u bazi, te ponovni unos JMBG.

**Comment by mathildaa** [comment]
http://pokit.org/get/?e52d00fd3daccc4aa13aa715aa29e912.jpg

mislim da ovo spada pod duplanje, već je prijavljeno:  https://github.com/SoftverInzenjeringETFSA/SI2015Tim12/issues/15
