### ISSUE TITLE
Unhandled exception prilikom prikaza rezervacija

### ISSUE THREAD

**Issue by anogo1** [SoftverInzenjeringETFSA/SI2015Tim12#29]
Komponenta:
Forma Rezervacije

commit ID:
e047178

Opis problema:
Postojeće rezervacije se ne prikažu, dolazi do unhandled exception-a.

Koraci za reproduciranje problema:
1. Pokretanje aplikacije
2. Prijava pomocu podataka username: kagent  password: Sitim12
3. Odabir opcije Rezervacije na prikazanoj formi

Dobijeni rezultat:
http://pokit.org/get/?8a00810b467c9a2d921579e318fe1ef9.png
http://pokit.org/get/?c84e122ca7981e82ca6994c4e52ec4c7.png

Očekivani rezultat:
Prikaz postojećih rezervacija ili eventualno obavijest da se rezervacije ne mogu učitati zbog određenog razloga
http://pokit.org/get/?9bce0d55f9cbaf15febbd3e55f08bdcb.png

**Comment by srepuh** [comment]
Da li si mijenjao podatke u bazi rucno, provjeri da li ti je ova baza importovana
d40e5ea858b20d4fa609ce0abcddd0f6e4153d2e

**Comment by anogo1** [comment]
nije ništa mijenjano u bazi, i jeste ta importovana

**Comment by srepuh** [comment]
Ma nije mi jasno kako svima radi samo tebi ne, jer niko to jos nije prijavio, a prijavili su druge stvari koje se tu desavaju... :/

**Comment by adnatahic** [comment]
Da li ti se hoteli mogu izlistati? Ovo svima radi, kako nama, tako i drugim testerima, tako da nisi fino povezao sa bazom.
