### ISSUE TITLE
Neispravna validacija prilikom kreiranja rezervacije

### ISSUE THREAD

**Issue by anogo1** [SoftverInzenjeringETFSA/SI2015Tim12#30]
Komponenta:
Forma Kreiranje Rezervacije

commit ID:
efbe122

Opis problema:
Za polja Ime i Prezime bi trebalo omogućiti samo unos slova(ne i brojeva i eventualno nekih specijalnih znakova), te bi trebalo zabraniti da se datum rođenja osobe može postaviti za datum u budućnosti

Koraci za reproduciranje problema:
1. Pokretanje aplikacije
2. Prijava pomocu podataka username: kagent password: Sitim12
3. Odabir opcije Rezervacije na prikazanoj formi
4. Odabir opcije Kreiraj Rezervaciju
5. Unos nevalidnih podataka
6. Rezervacija je uspješno kreirana

Dobijeni rezultat:
http://pokit.org/get/?9f9b492e8049d9b08c54ebc49844eef6.png

Očekivani rezultat:
Obavijest da navedena polja nisu validno unesena

**Comment by srepuh** [comment]
Popravljeno 2050348b5e294aa1d22d2523e19d687ab169abab

**Comment by anogo1** [comment]
Idalje je moguće datum rođenja postaviti na neki datum u budućnosti prilikom kreiranja rezervacije.
http://pokit.org/get/?8398c85bab01fdee1d2898979f13dfaf.png
