### ISSUE TITLE
Nemogućnost kreiranja rezervacije

### ISSUE THREAD

**Issue by anogo1** [SoftverInzenjeringETFSA/SI2015Tim12#31]
Komponenta:
Forma Kreiranje Rezervacije

commit ID:
efbe122

Opis problema:
Nije moguće kreirati rezervaciju za kreirani hotel

Koraci za reproduciranje problema:
1. Pokretanje aplikacije
2. Prijava pomocu podataka username: kagent password: Sitim12
3. Odabir opcije Hoteli u ponudi
4. Odabir opcije Dodaj Hotel
5. Unos svih traženih informacija, te potvrda klikom na dugme Dodaj hotel
http://pokit.org/get/?ddb5f91c56fcc2c935e789844d53f8e8.png
6. Povratak na formu Pregled hotela
7. Selektovanje hotela te odabir opcije Pregledaj sobe
http://pokit.org/get/?e19131744d98a03abb0c4001d552f981.png
8. Unos potrebnih informacija, te dodavanje novih soba
http://pokit.org/get/?ab4ccbb66079df1dfb774e3bca0c438b.png
http://pokit.org/get/?c481fe391608166963881fc049b9c314.png
9. Odlazak na formu Rezervacije pomoću menija
10. Odabir opcije Kreiraj rezervaciju
11. Odabir hotela koji je prethodno napravljen te unos svih potrebnih informacija

Dobijeni rezultat:
http://pokit.org/get/?00475a5b961c1afc74a791440d06cd4a.png
http://pokit.org/get/?de8fab5031e0bb81bbb3a42c62863ab8.png

Očekivani rezultat:
Uspješno kreiranje rezervacije ili eventualno poruka o nemogućnosti kreiranja rezervacije trenutno, a ne da nije odabrana soba

**Comment by adnatahic** [comment]
ispravljeno u commitu: 939eaaa4f10adbc03a19b68dd89f1b0437af94ca
