### ISSUE TITLE
Izuzetak i krahiranje programa prilikom prijave na sistem

### ISSUE THREAD

**Issue by psimanic1** [SoftverInzenjeringETFSA/SI2015Tim12#33]
Komponenta: 
Prijava na sistem

commit ID:
ba53af7

Opis problema:
Ukoliko se unese username duži od 45 karaktera dolazi do izuzetka.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. U polje "Korisničko ime" na Login formi unijeti username koji sadrži više od 45 karaktera.

Dobijeni rezultat: unhandled exception

Očekivani rezultat:
Obavještenje da je prekorače broj dozvoljenih karaktera, te traženje ponovnog unosa.

**Comment by kprses** [comment]
Taj se exception dešavao zbog toga što taj korisnik nije postojao u bazi podataka a to je bug koji je prijavljen kroz issue #28 i upravo je to riješeno korz commit 4c2139d841638be308e5af82c96f61f00d06d59c koji je riješio i issue #28
