### ISSUE TITLE
Neusaglašenost koda i SRS-a

### ISSUE THREAD

**Issue by anogo1** [SoftverInzenjeringETFSA/SI2015Tim12#34]
Komponenta:
Forma Prikaz Klijenata
SRS_v2
https://github.com/SoftverInzenjeringETFSA/SI2015Tim12/blob/master/Dokumentacija/SRS_v2.pdf

commit ID:
e047178

Opis problema:
U SRS-u, u funkcionalnom zahtjevu 3.2.13 Pregled klijenata, je navedeno da administrator/supervizor mora prvo odabrati klijenta o kojem želi prikaz, te da će mu se prikazati podaci o tom klijentu. Također je navedeno da sistem omogućava unos ključne riječi za pretragu klijenata, što nije slučaj.

Koraci reproduciranja problema:
1. Pokretanje aplikacije
2. Prijava pomocu podataka username: kenanprses password: Sitim12
3. Odabir opcije Klijenti

Dobijeni rezultat:
http://pokit.org/get/?c1f4e5077ca5f6f9f17eb0d03a0d508b.png

Očekivani rezultat:
Prikaz forme u kojoj je pomoću pretrage ključne riječi moguće odabrati klijenta za kojeg se žele prikazati podaci.

**Comment by adnatahic** [comment]
Duplikat #22
