### ISSUE TITLE
Unhandled exception prilikom potvrde rezervacije i otkazivanja rezervacije

### ISSUE THREAD

**Issue by anogo1** [SoftverInzenjeringETFSA/SI2015Tim12#36]
Komponenta:
Forma Rezervacije

commit ID:
e047178

Opis problema:
Ukoliko nije odabrana niti jedna rezervacija, odabirom opcija Potvrdi i Otkaži rezervaciju, dolazi do unhandled exception-a.

Koraci za reproduciranje problema:
1. Pokretanje aplikacije
2. Prijava pomocu podataka username: kenanprses password: Sitim12
3. Odabir opcije Potvrdi rezervaciju ili Otkaži rezervaciju

Dobijeni rezultat:
http://pokit.org/get/?02abffd51dd1885f6a2273890d988fd4.png
http://pokit.org/get/?af10adecbe97e46ab1422a1d06488486.png

Očekivani rezultat:
Obavijest da nijedna rezervacija nije odabrana(kao kada se odabere opcija Izdaj fakturu na istoj formi)
http://pokit.org/get/?11997ed7c8d065668563c81d8239262a.png

**Comment by srepuh** [comment]
Popravljeno 2050348b5e294aa1d22d2523e19d687ab169abab
