### ISSUE TITLE
Neispravnost prilikom modifikacije korisnika

### ISSUE THREAD

**Issue by anogo1** [SoftverInzenjeringETFSA/SI2015Tim12#37]
Komponenta:
Forma Modifikacija korisnika

commit ID:
e047178

Opis problema:
U bazi podataka su se već nalazili korisnici sa određenim podacima koji ne prolaze validaciju, te se eventualnim modifikovanjem nekog validnog podatka moraju i ti podaci promijeniti. Modifikacijom podataka jednog korisnika je došlo do modifikacije više korisnika.

Koraci za reproduciranje problema:
1. Pokretanje aplikacije
2. Prijava pomocu podataka username: kenanprses password: Sitim12
3. Odabir opcije Korisnici
4. Selektovanje prvog korisnika, ime Kenan, prezime Prses, tip korisnika Administrator
5. Odabir opcije Modifikuj korisnika
6. Promjena imena korisnika u Ahmet, te tipa korisnika u Supervizor
7. Odabir opcije Ažuriraj
8. Prepravljanje polja JMBG i Broj lične karte u prihvatljive vrijednosti

Dobijeni rezultat:
http://pokit.org/get/?affc92296fbed603a7517ea4a49c1e9b.png
http://pokit.org/get/?b05c69d1624ce4fa8f3087918ebbd786.png

Očekivani rezultat:
Promjena podataka samo korisnika koji je odabran, te onemogućavanje modificiranja korisnika tako da se dobiju dva korisnika sa identičnim podacima.

**Comment by kprses** [comment]
Ova greška se desila zato što su u bazi podataka navedeni korisnici ručno unijeti a onemogućavanje unosa istog korisnika je urađeno na vrijeme tj prije 15.-og u commitu ba53af70c39633c163a1f21efa69d700a789f676 .
