### ISSUE TITLE
Unhandled exception prilikom modifikacije i brisanja korisnika

### ISSUE THREAD

**Issue by anogo1** [SoftverInzenjeringETFSA/SI2015Tim12#38]
Komponenta:
Forma Prikaz korisnika

commit ID:
e047178

Opis problema:
Ukoliko se ne selektuje nijedan korisnik, dolazi do unhandled exception-a prilikom odabira opcije Modifikuj korisnika ili Obriši korisnika(postavi se i pitanje da li želimo obrisati korisnika, iako ga nismo odabrali).

Koraci za reproduciranje problema:
1. Pokretanje aplikacije
2. Prijava pomocu podataka username: kenanprses password: Sitim12
3. Odabir opcije Korisnici
4. Odabir opcije Modifikuj korisnika ili Obriši korisnika

Dobijeni rezultat:
http://pokit.org/get/?3518c9c7e1450ee3fcc5b8ec28706554.png
http://pokit.org/get/?c41995bd6f88bbcb26f47b0e67d171df.png
http://pokit.org/get/?ff07d837e002b35546dbdc276ff23113.png

Očekivani rezultat:
Obavijest da nije odabran nijedan korisnik.

**Comment by kprses** [comment]
Prema SRS-u ulaz u proces brisanja ili modifikacije je odabrani korisnik. U ovom slučaju nije odabran niti jedan korisnik. A klik na dugme "Obriši kornika" ili "Modifikuj korisnika" se ne odražava na rad aplikacije. Korisnik može normalno nastaviti rad u aplikaciji. 
Što se tiče popupa on služi samo da spriječi slučajne greške koje korisnik može napraviti.

**Comment by anogo1** [comment]
Dva issue-a #50 i #51 su označeni kao validan bug i riješeni, iako je ovdje već opisan problem za oba issue-a, a ovaj issue je označen kao invalid.
