### ISSUE TITLE
Mogućnost ažuriranja tabela

### ISSUE THREAD

**Issue by mathildaa** [SoftverInzenjeringETFSA/SI2015Tim12#39]
Komponenta:
Bilo koja forma koja prikazuje hotele, rezervacije, korisnike, tj bilo koja forma koja sadrži tabelu

commit ID:
efbe122

Opis problema:
Mogućnost izmjene podataka u tabelama (npr promjena imena), ali se ta promjena ne odražava na bazu, nije implementirano

Koraci reproduciranja problema:
1. Pokretanje aplikacije
2. Prijava pomocu podataka username: kenanprses password: Sitim12
3. Odabir opcije Korisnici
4. U tabeli promijeniti neki podatak
5. U bazi se nije promijenio taj podatak

Dobijeni rezultat:
http://pokit.org/get/?6b676848b6b3af6a51f56b443f83d036.jpg

Očekivani rezultat:
Ili promjena u bazi, ili nemogućnost promjene u tabeli

**Comment by adnatahic** [comment]
ispravljeno
