### ISSUE TITLE
Neslaganje validacije sa SRSom za unos emaila

### ISSUE THREAD

**Issue by mathildaa** [SoftverInzenjeringETFSA/SI2015Tim12#41]
Komponenta:
Kreiranje rezervacije

commit ID:
efbe122

Opis problema:
Nemogućnost kreiranje rezervacije bez unosa emaila klijenta, dok je to u srs-u pretpostavljeno da se ne mora unijeti: http://pokit.org/get/?e1da58977678892360c9fa64f0ade4d6.jpg

Koraci reproduciranja problema:
1. Pokretanje aplikacije
2. Prijava pomocu podataka username: kenanprses password: Sitim12
3. Odabir opcije Rezervacije
4. Popuniti sve podatke osim emaila
5. Kliknuti na Potvrdi

Dobijeni rezultat:
http://pokit.org/get/?89a5229d776ef2e3a359214e5230b635.jpg

Očekivani rezultat:
Uspješna registracija

**Comment by srepuh** [comment]
#35
