### ISSUE TITLE
Funckionalnost se ne podudara sa SRS-om

### ISSUE THREAD

**Issue by ncongo** [SoftverInzenjeringETFSA/SI2015Tim12#48]
Komponenta: Početna forma za supervizora

Commit id: bdbe35d

Opis problema: Nisu omogućene opcije koje su navedene u SRS-u za određenog korisnika

Koraci za reproduciranje problema:
1. Pokretanje aplikacije
2. Prijava na sistem sa podacima: korisničko ime: ksupervizor, šifra Sitim12

Dobijeni rezultat:
Forma na kojoj se nalaze opcije koje su onemogućene iako je prikazana poruka da sam prijavljena kao supervizor. http://prntscr.com/b5z2jy
U SRS-u je navedeno da supervizor ima sljedeće mogućnosti: http://prntscr.com/b5z2t3

Očekivani rezultat: Forma na kojoj su omogućene opcije koje su navedene u SRS-u

Navedeno se dešava i sa prijavom kao putnički agent. Sa podacima: korisničko ime: Tkorisnik, šifra Tsifra
http://prntscr.com/b5z3t9
U SRS-u je navedeno da su mogućnosti putničkog agenta sljedeće sljedeće: http://prntscr.com/b5z4b8

**Comment by kprses** [comment]
Na sljedećoj slici je prikazana početna forma za putničkog agenta:
![image](https://cloud.githubusercontent.com/assets/11404450/15404075/2b084d32-1dfc-11e6-864b-0f65487ad314.png)

Ovo su moduli kojima putnički agent ima pristup ako su mu omogućeni od starne administratora (Što je u skladu sa SRS-om). Kroz ove module putnički agent ima mogućnosti koje su navedene u SRS-u.

Isti slučaj je i sa korsnikom tipa supervizor. I on ima pristup određenim modulima ako su mu omogućene od strane adnimistratora (U skladu sa SRS-om).

Sve module u aplikaciji administrira korisnik tipa administrator i to kroz modul "Postavke". On može omogućiti/onemogućiti ostale module.
