### ISSUE TITLE
3.2.8 i 3.2.9

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2015Tim12#6]
3.2.8 i 3.2.9 mi se čini duplirano. Ako pravite hotel i ugovor posebno, onda na hotelu idu osnovni podaci naziv, lokacija, a ostalo u ugovor.

**Comment by kprses** [comment]
Iz SRS-a smo izbacili pojam ugovor za hotel sada imamo pojam hotel.
